version: '3.9'

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres_container
    environment:
      - POSTGRESQL_DATABASE=${DB_DATABASE}
      - POSTGRESQL_USERNAME=${DB_USERNAME}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/bitnami/postgresql
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
